# Template: Advanced Configuration Guide
# Template ID: advanced_configuration
# Intent Type: practitioner
# Coverage: 34 keywords (multi-company, multi-warehouse, multi-currency, localization, advanced modules)
# Variables Required: {{configuration_focus}}, {{odoo_version}}, {{business_complexity}}, {{industry_type}}
# Reusable Modules: configuration/{{configuration_focus}}_setup.yml, localization/{{country_code}}.yml

metadata:
  title: "{{configuration_topic}} in Odoo {{odoo_version}}: Advanced Configuration Guide"
  description: "Configure {{configuration_topic}} in Odoo {{odoo_version}}. Master complex business scenarios including {{business_complexity}} setups. Step-by-step implementation with best practices."
  intent_type: "practitioner"
  page_slug: "{{configuration_slug}}"
  draft_metadata:
    created_by: "pseo-bulk-generator"
    template_id: "advanced_configuration"
    generation_mode: "template"
    confidence_level: "high"
    notes_for_reviewer: "Verify configuration steps match Odoo {{odoo_version}} UI. Check localization requirements are current."

static_data:
  # Configuration Context
  configuration_focus: "{{configuration_focus}}"  # multi-company/multi-warehouse/multi-currency/localization/advanced-accounting
  odoo_version: "{{odoo_version}}"
  business_complexity: "{{business_complexity}}"  # single-entity/multi-entity/global/conglomerate
  industry_type: "{{industry_type}}"  # manufacturing/retail/service/distribution
  user_count: "{{user_count}}"
  transaction_volume: "{{monthly_transactions}}"

  # Business Structure
  organizational_structure:
    company_structure:
      parent_company: "{{parent_company}}"
      subsidiaries: "{{subsidiary_count}}"
      branches: "{{branch_count}}"
      legal_entities: "{{legal_entity_count}}"

    operational_model:
      business_units: ["{{bu_1}}", "{{bu_2}}", "{{bu_3}}"]
      shared_services: ["{{service_1}}", "{{service_2}}"]
      profit_centers: "{{profit_center_count}}"
      cost_centers: "{{cost_center_count}}"

    geographical_presence:
      countries: "{{country_count}}"
      currencies: "{{currency_count}}"
      languages: "{{language_count}}"
      time_zones: "{{timezone_count}}"

  # Configuration Architecture
  configuration_phases:
    - phase: 1
      title: "Requirements Analysis & Design"
      duration: "2-3 days"
      tasks:
        - task: "Business process mapping"
          deliverables:
            - "Current state process flows"
            - "Future state design"
            - "Gap analysis"
            - "Configuration requirements document"

        - task: "Data structure planning"
          components:
            - component: "Company hierarchy"
              complexity: "{{hierarchy_levels}}"
            - component: "Chart of accounts"
              accounts: "{{account_count}}"
            - component: "Product categories"
              categories: "{{category_count}}"
            - component: "Partner categories"
              types: ["Customer", "Vendor", "Both", "Employee"]

        - task: "Security matrix design"
          security_design:
            user_groups: "{{group_count}}"
            access_levels: ["Read", "Write", "Create", "Delete"]
            record_rules: "{{rule_count}}"
            field_level_security: "{{field_security_enabled}}"

        - task: "Integration requirements"
          integrations:
            - system: "{{integration_1}}"
              type: "{{integration_type_1}}"
            - system: "{{integration_2}}"
              type: "{{integration_type_2}}"

      verification: "Sign-off on configuration blueprint"

    - phase: 2
      title: "Multi-Company Configuration"
      duration: "3-4 days"
      tasks:
        - task: "Create company structure"
          steps:
            - step: "Define parent company"
              settings:
                name: "{{parent_name}}"
                currency: "{{parent_currency}}"
                country: "{{parent_country}}"
                tax_id: "{{parent_tax_id}}"

            - step: "Add subsidiary companies"
              template: |
                Company Name: {{subsidiary_name}}
                Parent Company: {{parent_reference}}
                Currency: {{subsidiary_currency}}
                Inter-company transactions: {{intercompany_enabled}}
                Consolidation: {{consolidation_enabled}}

            - step: "Configure company switching"
              options:
                allow_multi_company: true
                company_dependent_fields: ["{{field_1}}", "{{field_2}}"]
                default_company_selection: "{{default_company_rule}}"

        - task: "Inter-company transactions setup"
          intercompany_rules:
            - rule: "Sales to Purchase"
              auto_generate: "{{so_to_po_enabled}}"
              validation: "{{validation_required}}"
            - rule: "Invoice to Bill"
              auto_generate: "{{invoice_to_bill_enabled}}"
              sync_method: "{{sync_method}}"
            - rule: "Stock transfers"
              transit_location: "{{transit_location}}"

        - task: "Consolidated reporting"
          consolidation_setup:
            method: "{{consolidation_method}}"  # full/proportional/equity
            elimination_entries: "{{elimination_enabled}}"
            currency_translation: "{{translation_method}}"
            reporting_frequency: "{{consolidation_frequency}}"

      verification: "Test inter-company transaction flow"

    - phase: 3
      title: "Multi-Warehouse & Inventory Configuration"
      duration: "2-3 days"
      tasks:
        - task: "Warehouse structure setup"
          warehouse_configuration:
            - warehouse: "Main Warehouse"
              code: "{{main_wh_code}}"
              type: "{{main_wh_type}}"  # physical/virtual/transit
              locations:
                - "Stock"
                - "Input"
                - "Output"
                - "Packing Zone"
                - "Quality Control"

            - warehouse: "Regional Distribution"
              code: "{{regional_wh_code}}"
              type: "{{regional_wh_type}}"
              resupply_from: "{{resupply_warehouse}}"
              resupply_route: "{{resupply_method}}"

        - task: "Routes and rules configuration"
          routing_rules:
            - route: "Dropship"
              steps: "{{dropship_steps}}"
              auto_enabled: "{{dropship_auto}}"

            - route: "Cross-Dock"
              steps: "{{crossdock_steps}}"
              conditions: "{{crossdock_conditions}}"

            - route: "Make-to-Order"
              trigger: "{{mto_trigger}}"
              lead_time: "{{mto_lead_days}} days"

        - task: "Inventory valuation setup"
          valuation_config:
            costing_method: "{{costing_method}}"  # standard/average/fifo/lifo
            inventory_valuation: "{{valuation_type}}"  # manual/automated
            stock_accounts:
              input: "{{stock_input_account}}"
              output: "{{stock_output_account}}"
              valuation: "{{stock_valuation_account}}"

        - task: "Replenishment strategies"
          replenishment_rules:
            method: "{{replenishment_method}}"  # min-max/mto/leadtime
            frequency: "{{replenishment_frequency}}"
            safety_stock: "{{safety_stock_days}} days"
            reorder_rules: "{{reorder_rule_count}}"

      verification: "Simulate full procurement cycle"

    - phase: 4
      title: "Multi-Currency & Localization"
      duration: "2-3 days"
      tasks:
        - task: "Currency configuration"
          currency_setup:
            main_currency: "{{main_currency}}"
            additional_currencies: ["{{currency_1}}", "{{currency_2}}", "{{currency_3}}"]
            rate_update:
              provider: "{{rate_provider}}"  # ECB/xe.com/manual
              frequency: "{{update_frequency}}"
              automatic: "{{auto_update_enabled}}"

            gain_loss_accounts:
              exchange_gain: "{{gain_account}}"
              exchange_loss: "{{loss_account}}"

        - task: "Localization package"
          localization_config:
            country: "{{localization_country}}"
            fiscal_position: "{{fiscal_positions_count}}"
            tax_configuration:
              sales_tax: "{{sales_tax_rate}}%"
              purchase_tax: "{{purchase_tax_rate}}%"
              withholding: "{{withholding_enabled}}"

            regulatory_reports:
              - report: "{{report_1}}"
                frequency: "{{report_1_frequency}}"
              - report: "{{report_2}}"
                frequency: "{{report_2_frequency}}"

        - task: "Payment terms and methods"
          payment_configuration:
            payment_terms:
              - term: "{{term_1}}"
                days: "{{term_1_days}}"
                discount: "{{term_1_discount}}%"
              - term: "{{term_2}}"
                days: "{{term_2_days}}"

            payment_methods:
              - method: "{{payment_method_1}}"
                journal: "{{journal_1}}"
              - method: "{{payment_method_2}}"
                journal: "{{journal_2}}"

        - task: "Fiscal positions"
          fiscal_position_mapping:
            automatic_detection: "{{auto_fiscal_position}}"
            rules:
              - country: "{{country_1}}"
                position: "{{fiscal_position_1}}"
              - country: "{{country_2}}"
                position: "{{fiscal_position_2}}"

      verification: "Multi-currency transaction test"

    - phase: 5
      title: "Advanced Accounting Configuration"
      duration: "3-4 days"
      tasks:
        - task: "Chart of accounts setup"
          coa_configuration:
            template: "{{coa_template}}"
            account_types:
              assets: "{{asset_accounts}}"
              liabilities: "{{liability_accounts}}"
              income: "{{income_accounts}}"
              expenses: "{{expense_accounts}}"
              equity: "{{equity_accounts}}"

            analytic_accounting:
              dimensions: "{{analytic_dimensions}}"
              plans: ["{{plan_1}}", "{{plan_2}}"]
              distribution_models: "{{distribution_model_count}}"

        - task: "Cost center configuration"
          cost_accounting:
            cost_centers: "{{cost_center_list}}"
            allocation_rules:
              - rule: "{{allocation_rule_1}}"
                basis: "{{allocation_basis_1}}"
              - rule: "{{allocation_rule_2}}"
                basis: "{{allocation_basis_2}}"

        - task: "Budget management"
          budget_configuration:
            budget_types: ["{{budget_type_1}}", "{{budget_type_2}}"]
            approval_workflow:
              levels: "{{approval_levels}}"
              threshold_amounts: "{{threshold_list}}"

            variance_alerts:
              threshold: "{{variance_threshold}}%"
              notification: "{{notification_method}}"

        - task: "Financial reports customization"
          report_configuration:
            standard_reports:
              - "Balance Sheet"
              - "Profit & Loss"
              - "Cash Flow Statement"
              - "General Ledger"

            custom_reports:
              - name: "{{custom_report_1}}"
                type: "{{report_type_1}}"
              - name: "{{custom_report_2}}"
                type: "{{report_type_2}}"

      verification: "Run trial balance and verify"

    - phase: 6
      title: "Advanced Module Configuration"
      duration: "2-3 days"
      tasks:
        - task: "Manufacturing configuration"
          mrp_setup:
            production_planning:
              method: "{{planning_method}}"  # mts/mto/hybrid
              scheduling: "{{scheduling_type}}"  # forward/backward

            bill_of_materials:
              multi_level: "{{multi_level_bom}}"
              variants: "{{variant_bom_enabled}}"
              subcontracting: "{{subcontracting_enabled}}"

            work_centers:
              count: "{{workcenter_count}}"
              efficiency_tracking: "{{oee_enabled}}"
              capacity_planning: "{{capacity_planning_enabled}}"

        - task: "CRM advanced features"
          crm_configuration:
            sales_teams: "{{sales_team_count}}"
            lead_scoring:
              enabled: "{{lead_scoring_enabled}}"
              criteria: ["{{criteria_1}}", "{{criteria_2}}"]

            pipeline_automation:
              stages: "{{pipeline_stages}}"
              automation_rules: "{{automation_rule_count}}"

        - task: "Project management setup"
          project_configuration:
            project_stages: ["{{stage_1}}", "{{stage_2}}", "{{stage_3}}"]
            task_dependencies: "{{dependencies_enabled}}"
            resource_planning: "{{resource_planning_enabled}}"

            billing_methods:
              - method: "Fixed Price"
              - method: "Time & Materials"
              - method: "Milestone"

      verification: "Test complete business cycle"

    - phase: 7
      title: "Automation & Workflows"
      duration: "2-3 days"
      tasks:
        - task: "Automated actions"
          automation_rules:
            - trigger: "{{trigger_1}}"
              action: "{{action_1}}"
              condition: "{{condition_1}}"

            - trigger: "{{trigger_2}}"
              action: "{{action_2}}"
              condition: "{{condition_2}}"

        - task: "Approval workflows"
          approval_configuration:
            purchase_approval:
              levels: "{{po_approval_levels}}"
              amounts: "{{po_threshold_amounts}}"

            expense_approval:
              levels: "{{expense_approval_levels}}"
              delegation: "{{delegation_enabled}}"

        - task: "Scheduled actions"
          cron_jobs:
            - name: "{{cron_1}}"
              frequency: "{{cron_1_frequency}}"
              action: "{{cron_1_action}}"

            - name: "{{cron_2}}"
              frequency: "{{cron_2_frequency}}"
              action: "{{cron_2_action}}"

        - task: "Email templates"
          email_automation:
            templates: "{{template_count}}"
            triggers: ["{{email_trigger_1}}", "{{email_trigger_2}}"]
            dynamic_content: "{{dynamic_content_enabled}}"

      verification: "Test all automated workflows"

    - phase: 8
      title: "Security & Access Control"
      duration: "1-2 days"
      tasks:
        - task: "User groups configuration"
          group_setup:
            standard_groups:
              - group: "{{group_1}}"
                access_level: "{{access_1}}"
              - group: "{{group_2}}"
                access_level: "{{access_2}}"

            custom_groups:
              count: "{{custom_group_count}}"
              inheritance: "{{inheritance_structure}}"

        - task: "Record rules"
          access_rules:
            global_rules: "{{global_rule_count}}"
            company_rules: "{{company_rule_count}}"
            user_specific: "{{user_rule_count}}"

            domain_filters:
              - rule: "{{rule_name_1}}"
                domain: "{{domain_1}}"
              - rule: "{{rule_name_2}}"
                domain: "{{domain_2}}"

        - task: "Field-level security"
          field_security:
            sensitive_fields: ["{{field_1}}", "{{field_2}}", "{{field_3}}"]
            encryption: "{{field_encryption_enabled}}"
            audit_trail: "{{audit_enabled}}"

      verification: "Security audit and penetration test"

  # Configuration Best Practices
  best_practices:
    data_management:
      - practice: "Regular data cleanup"
        frequency: "{{cleanup_frequency}}"
      - practice: "Archive old records"
        retention: "{{retention_period}}"
      - practice: "Duplicate detection"
        method: "{{duplicate_detection_method}}"

    performance:
      - practice: "Index optimization"
        indexes: "{{custom_index_count}}"
      - practice: "Batch processing"
        batch_size: "{{batch_size}}"
      - practice: "Async processing"
        jobs: "{{async_job_count}}"

    compliance:
      - practice: "Audit logging"
        retention: "{{audit_retention_days}} days"
      - practice: "Data privacy"
        gdpr_compliant: "{{gdpr_compliant}}"
      - practice: "Change management"
        approval_required: "{{change_approval}}"

  # Testing Strategy
  testing_approach:
    test_scenarios:
      - scenario: "End-to-end business flow"
        coverage: "{{e2e_coverage}}%"
      - scenario: "Multi-company transactions"
        test_cases: "{{multi_company_tests}}"
      - scenario: "Currency conversion"
        test_cases: "{{currency_tests}}"
      - scenario: "Access control"
        test_cases: "{{security_tests}}"

    acceptance_criteria:
      functional: "{{functional_criteria}}"
      performance: "{{performance_criteria}}"
      security: "{{security_criteria}}"
      compliance: "{{compliance_criteria}}"

  # Change Management
  change_management:
    training_plan:
      user_groups: ["{{training_group_1}}", "{{training_group_2}}"]
      training_hours: "{{total_training_hours}}"
      materials: ["User guides", "Video tutorials", "Quick reference cards"]

    rollout_strategy:
      approach: "{{rollout_approach}}"  # big-bang/phased/parallel
      phases: "{{rollout_phases}}"
      rollback_plan: "{{rollback_documented}}"

    support_structure:
      help_desk: "{{helpdesk_enabled}}"
      documentation: "{{documentation_complete}}"
      super_users: "{{super_user_count}}"

# AI-generated content sections (filled by enrichment pipeline)
ai_generated_content:
  introduction: ""
  step_by_step_guide: ""  # Main configuration guide content (standard field)
  troubleshooting_guide: ""
  conclusion: ""

# Conversion assets (filled by pseo-conversion-copywriter)
conversion_assets:
  - component_type: "callout-box"
    placement_hint: "mid_guide"
    generated_copy: {}

  - component_type: "benefit-list"
    placement_hint: "post_technical"
    generated_copy: {}

  - component_type: "product-box"
    placement_hint: "pre_conclusion"
    generated_copy: {}

# Intelligent internal links (filled by pseo-link-architect)
intelligent_links:
  - link_type: "related-configuration"
    placement: "in-content"
    generated_link: {}

  - link_type: "module-guide"
    placement: "after-modules"
    generated_link: {}

  - link_type: "best-practices"
    placement: "footer"
    generated_link: {}

# Visualizations (filled by pseo-visualization-agent)
visualizations:
  - chart_type: "mermaid"
    title: "Company Structure Diagram"
    placement_hint: "after_steps"
    mermaid_chart_syntax: ""

  - chart_type: "mermaid"
    title: "Workflow Automation Map"
    placement_hint: "after_troubleshooting"
    mermaid_chart_syntax: ""