# NGINX Configuration for Odoo - Common Module
# Last Updated: 2025-10-27
# Applicable to: NGINX 1.18+, Odoo 14-17
# Verification Status: ✅ VERIFIED

# Basic Reverse Proxy Configuration
basic_config:
  description: "Standard NGINX reverse proxy for single Odoo instance"
  config_file: "/etc/nginx/sites-available/odoo"

  http_block:
    upstream_odoo:
      server: "127.0.0.1:8069"

    upstream_odoo_chat:
      server: "127.0.0.1:8072"

    server:
      listen: 80
      server_name: "odoo.example.com"

      # Redirect HTTP to HTTPS
      return: "301 https://$host$request_uri"

  https_block:
    server:
      listen: "443 ssl http2"
      server_name: "odoo.example.com"

      # SSL Configuration
      ssl_certificate: "/etc/letsencrypt/live/odoo.example.com/fullchain.pem"
      ssl_certificate_key: "/etc/letsencrypt/live/odoo.example.com/privkey.pem"
      ssl_session_timeout: "30m"
      ssl_protocols: "TLSv1.2 TLSv1.3"
      ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
      ssl_prefer_server_ciphers: "off"

      # Logging
      access_log: "/var/log/nginx/odoo.access.log"
      error_log: "/var/log/nginx/odoo.error.log"

      # Proxy Settings
      proxy_read_timeout: "720s"
      proxy_connect_timeout: "720s"
      proxy_send_timeout: "720s"
      proxy_set_header:
        - "X-Forwarded-Host $host"
        - "X-Forwarded-For $proxy_add_x_forwarded_for"
        - "X-Forwarded-Proto $scheme"
        - "X-Real-IP $remote_addr"
        - "Host $http_host"

      # File Upload Size
      client_max_body_size: "256M"

      # Proxy Buffers
      proxy_buffers: "16 64k"
      proxy_buffer_size: "128k"

      # Locations
      location_longpolling:
        path: "/longpolling"
        proxy_pass: "http://127.0.0.1:8072"

      location_root:
        path: "/"
        proxy_redirect: "off"
        proxy_pass: "http://127.0.0.1:8069"

# SSL/TLS Configuration (Let's Encrypt)
ssl_config:
  certbot_install:
    ubuntu_debian: "sudo apt install -y certbot python3-certbot-nginx"

  obtain_certificate:
    command: "sudo certbot --nginx -d odoo.example.com"

  auto_renewal:
    command: "sudo certbot renew --dry-run"
    cron_entry: "0 12 * * * /usr/bin/certbot renew --quiet"

# High Performance Configuration
performance_config:
  description: "Optimized for high traffic (100+ concurrent users)"

  nginx_conf_global:
    worker_processes: "auto"  # One per CPU core
    worker_connections: 2048
    use: "epoll"  # Linux
    multi_accept: "on"

  http_block:
    sendfile: "on"
    tcp_nopush: "on"
    tcp_nodelay: "on"
    keepalive_timeout: 65
    types_hash_max_size: 2048
    server_tokens: "off"  # Hide NGINX version

    # Gzip Compression
    gzip: "on"
    gzip_vary: "on"
    gzip_proxied: "any"
    gzip_comp_level: 6
    gzip_types: "text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml"
    gzip_disable: "msie6"

    # Client Body Buffer
    client_body_buffer_size: "128k"
    client_header_buffer_size: "1k"
    large_client_header_buffers: "4 16k"

    # Rate Limiting
    limit_req_zone: "$binary_remote_addr zone=odoo:10m rate=10r/s"
    limit_req: "zone=odoo burst=20 nodelay"

# Load Balancing Configuration
load_balancing_config:
  description: "Multi-server Odoo deployment with load balancing"

  upstream_odoo:
    servers:
      - "odoo-app1.internal:8069 weight=3"
      - "odoo-app2.internal:8069 weight=3"
      - "odoo-app3.internal:8069 weight=2 backup"  # Backup server

    options:
      ip_hash: true  # Session persistence
      keepalive: 32

  health_check:
    location: "/web/health"
    interval: "10s"
    fails: 3
    pass: 2

# Caching Configuration
caching_config:
  description: "Cache static assets to reduce Odoo load"

  proxy_cache_path: "/var/cache/nginx levels=1:2 keys_zone=odoo_cache:10m max_size=1g inactive=60m"

  location_static:
    path: "~* /web/static/"
    proxy_cache: "odoo_cache"
    proxy_cache_valid: "200 60m"
    proxy_cache_use_stale: "error timeout updating http_500 http_502 http_503 http_504"
    add_header: "X-Cache-Status $upstream_cache_status"
    expires: "7d"

# Security Headers
security_headers:
  add_header_directives:
    - "X-Frame-Options SAMEORIGIN always"
    - "X-Content-Type-Options nosniff always"
    - "X-XSS-Protection '1; mode=block' always"
    - "Referrer-Policy no-referrer-when-downgrade always"
    - "Content-Security-Policy \"default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:\" always"
    - "Strict-Transport-Security 'max-age=31536000; includeSubDomains' always"  # HSTS

# WebSocket Support (for Live Chat, POS)
websocket_config:
  location_websocket:
    path: "/websocket"
    proxy_pass: "http://127.0.0.1:8072"
    proxy_http_version: "1.1"
    proxy_set_header:
      - "Upgrade $http_upgrade"
      - "Connection 'upgrade'"
      - "Host $host"

# Complete Production-Ready Config Template
complete_config_template: |
  # Upstream Odoo
  upstream odoo {
    server 127.0.0.1:8069;
  }

  upstream odoo_chat {
    server 127.0.0.1:8072;
  }

  # HTTP to HTTPS Redirect
  server {
    listen 80;
    server_name odoo.example.com;
    return 301 https://$host$request_uri;
  }

  # HTTPS Server
  server {
    listen 443 ssl http2;
    server_name odoo.example.com;

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/odoo.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/odoo.example.com/privkey.pem;
    ssl_session_timeout 30m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers off;

    # Logging
    access_log /var/log/nginx/odoo.access.log;
    error_log /var/log/nginx/odoo.error.log;

    # Security Headers
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Proxy Settings
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_redirect off;

    # File Upload Size
    client_max_body_size 256M;

    # Proxy Buffers
    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    # Gzip
    gzip on;
    gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;

    # Longpolling (Live Updates, POS)
    location /longpolling {
      proxy_pass http://odoo_chat;
    }

    # Static Files Caching
    location ~* /web/static/ {
      proxy_cache_valid 200 90m;
      proxy_buffering on;
      expires 864000;
      proxy_pass http://odoo;
    }

    # Root Location
    location / {
      proxy_pass http://odoo;
    }
  }

# Common Commands
commands:
  test_config: "sudo nginx -t"
  reload: "sudo systemctl reload nginx"
  restart: "sudo systemctl restart nginx"
  enable_site: "sudo ln -s /etc/nginx/sites-available/odoo /etc/nginx/sites-enabled/"
  disable_site: "sudo rm /etc/nginx/sites-enabled/odoo"

# Troubleshooting
troubleshooting:
  - issue: "502 Bad Gateway"
    causes:
      - "Odoo service not running"
      - "Incorrect upstream port"
      - "Firewall blocking internal communication"
    solutions:
      - "Check Odoo status: sudo systemctl status odoo"
      - "Verify Odoo listening port: sudo netstat -tlnp | grep 8069"
      - "Check NGINX error log: sudo tail -f /var/log/nginx/error.log"

  - issue: "413 Request Entity Too Large"
    cause: "File upload exceeds client_max_body_size"
    solution: "Increase client_max_body_size in NGINX config and reload"

  - issue: "504 Gateway Timeout"
    cause: "Odoo response time exceeds proxy timeout"
    solution: "Increase proxy_read_timeout and proxy_send_timeout"

last_verified_date: "2025-10-27"
data_sources:
  - "NGINX Official Documentation"
  - "Odoo Deployment Best Practices"
  - "Mozilla SSL Configuration Generator"
